make freebsd documentation way better
ProcursusTeam/docs pull request #3
Opened 2021-08-02 14:56 UTC by asdfugil

2021-08-02 18:35 UTC, Doregon requested changes

2021-08-02 18:35 UTC, Doregon commented on Development/Building/FreeBSD.md
> +Export the location where you want to install the toolchain.
```suggestion
If you want to install the toolchain manually for whatever reason, begin with exporting the location where you want to install the toolchain.
```

Try making this more seamless than a cliffhanging sentence. The suggestion clips the two together. Other than this, it lgtm.

2021-08-03 00:14 UTC, Doregon approved these changes

2021-08-03 05:06 UTC, merged

2021-08-03 05:08 UTC, TheRealKeto commented
Why did you merge this?